"""Report PDF rendering (Phase 10) — clean, branded, downloadable reports.

Renders the daily and monthly manager reports to a formatted PDF with fpdf2
(pure Python, no native build — works on Python 3.14). Uses the core Helvetica
font, so text is transliterated to Latin-1 (smart quotes, dashes and bullets are
replaced with ASCII) to avoid font-embedding.

The output is raw PDF bytes, returned by the daemon with a
``application/pdf`` + ``Content-Disposition: attachment`` response so the
dashboard's "Download PDF" button saves a real file.
"""

from __future__ import annotations

from typing import List

from fpdf import FPDF
from fpdf.enums import XPos, YPos

from .models import DailyReport

# FlowState "lamplight" palette (RGB).
_AMBER = (180, 102, 30)
_INK = (42, 36, 32)
_MUTED = (110, 100, 86)

_REPL = {
    "—": "-", "–": "-", "’": "'", "‘": "'", "“": '"', "”": '"',
    "→": "->", "·": "-", "●": "-", "•": "-", "…": "...", "×": "x",
}


def _ascii(s: str) -> str:
    s = s or ""
    for k, v in _REPL.items():
        s = s.replace(k, v)
    return s.encode("latin-1", "ignore").decode("latin-1")


class _Doc(FPDF):
    def footer(self) -> None:
        self.set_y(-15)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(*_MUTED)
        self.cell(
            0, 10,
            _ascii("Generated by FlowState - local, private context restoration - 127.0.0.1"),
            align="C",
        )


def _title(pdf: _Doc, title: str, subtitle: str) -> None:
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(*_INK)
    pdf.cell(0, 10, _ascii(title), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    if subtitle:
        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(*_MUTED)
        pdf.cell(0, 7, _ascii(subtitle), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_draw_color(*_AMBER)
    pdf.set_line_width(0.8)
    y = pdf.get_y() + 2
    pdf.line(pdf.l_margin, y, pdf.w - pdf.r_margin, y)
    pdf.ln(6)


def _section(pdf: _Doc, heading: str, items: List[str]) -> None:
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(*_AMBER)
    pdf.cell(0, 8, _ascii(heading), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 11)
    if not items:
        pdf.set_text_color(*_MUTED)
        pdf.multi_cell(0, 6, _ascii("None recorded."), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    else:
        pdf.set_text_color(*_INK)
        for it in items:
            pdf.multi_cell(0, 6, _ascii("- " + str(it)), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(3)


def render_daily_pdf(report: DailyReport, date: str = "", workspace: str = "", user: str = "") -> bytes:
    pdf = _Doc()
    pdf.set_auto_page_break(True, margin=20)
    pdf.add_page()
    sub = " - ".join(
        x for x in [
            f"Date: {date}" if date else "",
            f"Workspace: {workspace}" if workspace else "",
            f"By: {user}" if user else "",
        ] if x
    )
    _title(pdf, "End-of-Day Progress Report", sub)
    _section(pdf, "Primary Objectives Tackled", report.primary_objectives)
    _section(pdf, "Files & Components Altered", report.files_components_altered)
    _section(pdf, "Cross-Tool Tasks Performed", report.cross_tool_tasks)
    _section(pdf, "End-of-Day Status & Blockers", report.status_and_blockers)
    return bytes(pdf.output())


def render_monthly_pdf(m: dict) -> bytes:
    pdf = _Doc()
    pdf.set_auto_page_break(True, margin=20)
    pdf.add_page()
    workspaces = ", ".join(m.get("workspaces", [])) or "-"
    _title(pdf, f"Monthly Progress Report - {m.get('month','')}",
           f"Days reported: {m.get('days_reported', 0)} - Workspaces: {workspaces}")
    _section(pdf, "At a Glance", [
        f"Days with reports: {m.get('days_reported', 0)}",
        f"Distinct files touched: {len(m.get('files_touched', []))}",
        f"Workspaces: {workspaces}",
    ])
    _section(pdf, "Objectives Across the Month", m.get("objectives", [])[:40])
    _section(pdf, "Files & Components Altered", m.get("files_touched", [])[:60])
    _section(pdf, "Cross-Tool Tasks", m.get("cross_tool_tasks", [])[:30])
    _section(pdf, "Open Items & Blockers", m.get("blockers", [])[:30])

    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(*_AMBER)
    pdf.cell(0, 8, _ascii("Daily Breakdown"), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*_INK)
    per_day = m.get("per_day", [])
    if not per_day:
        pdf.set_text_color(*_MUTED)
        pdf.multi_cell(0, 5, _ascii("No daily reports recorded this month."),
                       new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    for d in per_day:
        objectives = "; ".join(d.get("objectives", [])[:2]) or "(no objectives)"
        line = f"{d.get('date','')}  [{d.get('workspace','')}]  {objectives}"
        pdf.multi_cell(0, 5, _ascii(line), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    return bytes(pdf.output())
